/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PostId = IDL.Nat;
export const CommentId = IDL.Nat;
export const HighlightId = IDL.Nat;
export const StoryId = IDL.Nat;
export const UserId = IDL.Principal;
export const NoteAudience = IDL.Variant({
  'MutualFollowers' : IDL.Null,
  'CloseFriends' : IDL.Null,
});
export const Story = IDL.Record({
  'id' : StoryId,
  'songArtist' : IDL.Opt(IDL.Text),
  'songTitle' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'author' : UserId,
  'imageUrl' : IDL.Text,
  'caption' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'createdAt' : IDL.Int,
  'avatarUrl' : IDL.Text,
});
export const StoryWithUser = IDL.Record({
  'story' : Story,
  'authorProfile' : IDL.Opt(UserProfile),
});
export const ActivityStatus = IDL.Record({
  'isOnline' : IDL.Bool,
  'lastSeen' : IDL.Int,
});
export const Comment = IDL.Record({
  'id' : CommentId,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'author' : UserId,
  'postId' : PostId,
});
export const MessageId = IDL.Nat;
export const Message = IDL.Record({
  'id' : MessageId,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'toUser' : UserId,
  'fromUser' : UserId,
  'sharedPostId' : IDL.Opt(PostId),
});
export const ConversationSummary = IDL.Record({
  'userId' : UserId,
  'lastMessage' : IDL.Opt(Message),
  'profile' : IDL.Opt(UserProfile),
});
export const Post = IDL.Record({
  'id' : PostId,
  'songArtist' : IDL.Opt(IDL.Text),
  'hashtags' : IDL.Vec(IDL.Text),
  'imageUrls' : IDL.Vec(IDL.Text),
  'songTitle' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'isReel' : IDL.Bool,
  'author' : UserId,
  'imageUrl' : IDL.Text,
  'caption' : IDL.Text,
});
export const Note = IDL.Record({
  'expiresAt' : IDL.Int,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'audience' : NoteAudience,
  'author' : UserId,
});
export const NoteWithAuthor = IDL.Record({
  'likeCount' : IDL.Nat,
  'note' : Note,
  'authorProfile' : IDL.Opt(UserProfile),
});
export const Highlight = IDL.Record({
  'id' : HighlightId,
  'title' : IDL.Text,
  'owner' : UserId,
  'createdAt' : IDL.Int,
  'coverUrl' : IDL.Text,
  'storyIds' : IDL.Vec(StoryId),
});
export const DeviceInfo = IDL.Record({
  'deviceLabel' : IDL.Text,
  'addedAt' : IDL.Int,
  'deviceId' : IDL.Text,
  'principalId' : IDL.Text,
});
export const NotificationId = IDL.Nat;
export const Notification = IDL.Record({
  'id' : NotificationId,
  'kind' : IDL.Text,
  'createdAt' : IDL.Int,
  'isRead' : IDL.Bool,
  'toUser' : UserId,
  'fromUser' : UserId,
  'postId' : IDL.Opt(PostId),
});

export const idlService = IDL.Service({
  'addComment' : IDL.Func(
      [PostId, IDL.Text],
      [IDL.Variant({ 'ok' : CommentId, 'err' : IDL.Text })],
      [],
    ),
  'addQuestion' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'addReaction' : IDL.Func(
      [PostId, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'addStoryToHighlight' : IDL.Func(
      [HighlightId, StoryId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'addToCloseFriends' : IDL.Func(
      [UserId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'answerQuestion' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'authenticateWithPassword' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      ['query'],
    ),
  'blockUser' : IDL.Func([UserId], [], []),
  'createCarouselPost' : IDL.Func(
      [
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Variant({ 'ok' : PostId, 'err' : IDL.Text })],
      [],
    ),
  'createHighlight' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : HighlightId, 'err' : IDL.Text })],
      [],
    ),
  'createNote' : IDL.Func(
      [IDL.Text, NoteAudience],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'createPoll' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'createPost' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Bool,
      ],
      [IDL.Variant({ 'ok' : PostId, 'err' : IDL.Text })],
      [],
    ),
  'createProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'createQuestion' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'createStory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : StoryId, 'err' : IDL.Text })],
      [],
    ),
  'deleteHighlight' : IDL.Func(
      [HighlightId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteNote' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'downloadFile' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(IDL.Nat8), 'err' : IDL.Text })],
      ['query'],
    ),
  'followUser' : IDL.Func(
      [UserId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getActiveStories' : IDL.Func([], [IDL.Vec(StoryWithUser)], ['query']),
  'getActivityStatus' : IDL.Func([UserId], [ActivityStatus], ['query']),
  'getActivityStatusBatch' : IDL.Func(
      [IDL.Vec(UserId)],
      [IDL.Vec(IDL.Tuple(UserId, ActivityStatus))],
      ['query'],
    ),
  'getAllSetways' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getBlockedUsers' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
  'getCloseFriends' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCommentLikes' : IDL.Func([PostId, IDL.Nat], [IDL.Nat], ['query']),
  'getComments' : IDL.Func([PostId], [IDL.Vec(Comment)], ['query']),
  'getConversation' : IDL.Func([UserId], [IDL.Vec(Message)], ['query']),
  'getConversationList' : IDL.Func(
      [],
      [IDL.Vec(ConversationSummary)],
      ['query'],
    ),
  'getExploreFeed' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getFollowers' : IDL.Func([UserId], [IDL.Vec(UserProfile)], ['query']),
  'getFollowersNotes' : IDL.Func([], [IDL.Vec(NoteWithAuthor)], ['query']),
  'getFollowing' : IDL.Func([UserId], [IDL.Vec(UserProfile)], ['query']),
  'getHighlights' : IDL.Func([UserId], [IDL.Vec(Highlight)], ['query']),
  'getHomeFeed' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getLikeCount' : IDL.Func([PostId], [IDL.Nat], ['query']),
  'getMutedUsers' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
  'getMyDevices' : IDL.Func([], [IDL.Vec(DeviceInfo)], ['query']),
  'getMyNote' : IDL.Func([], [IDL.Opt(Note)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getMyPushToken' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getNoteLikes' : IDL.Func([UserId], [IDL.Vec(IDL.Principal)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPasswordUserPrincipal' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getPinnedPosts' : IDL.Func([UserId], [IDL.Vec(Post)], ['query']),
  'getPollResults' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'userVote' : IDL.Opt(IDL.Nat),
            'question' : IDL.Text,
            'votes' : IDL.Vec(IDL.Nat),
            'options' : IDL.Vec(IDL.Text),
          })
        ),
      ],
      ['query'],
    ),
  'getPost' : IDL.Func([PostId], [IDL.Opt(Post)], ['query']),
  'getPostImages' : IDL.Func([PostId], [IDL.Vec(IDL.Text)], ['query']),
  'getPostsByUser' : IDL.Func([UserId], [IDL.Vec(Post)], ['query']),
  'getProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'getProfileByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getQuestionAnswers' : IDL.Func(
      [IDL.Text],
      [
        IDL.Vec(
          IDL.Record({
            'answerer' : IDL.Text,
            'answer' : IDL.Text,
            'timestamp' : IDL.Int,
          })
        ),
      ],
      ['query'],
    ),
  'getReactions' : IDL.Func(
      [PostId],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getReelsFeed' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
  'getSavedPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getStories' : IDL.Func([UserId], [IDL.Vec(Story)], ['query']),
  'getStory' : IDL.Func([StoryId], [IDL.Opt(Story)], ['query']),
  'getTrendingHashtags' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'isBlocked' : IDL.Func([UserId], [IDL.Bool], ['query']),
  'isCloseFriend' : IDL.Func([UserId], [IDL.Bool], ['query']),
  'isCommentLiked' : IDL.Func([PostId, IDL.Nat], [IDL.Bool], ['query']),
  'isDeviceRegistered' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isFollowing' : IDL.Func([UserId], [IDL.Bool], ['query']),
  'isLiked' : IDL.Func([PostId], [IDL.Bool], ['query']),
  'isMuted' : IDL.Func([UserId], [IDL.Bool], ['query']),
  'likeComment' : IDL.Func(
      [PostId, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'likeNote' : IDL.Func(
      [UserId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'markNotificationsRead' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'muteUser' : IDL.Func([UserId], [], []),
  'pinPost' : IDL.Func(
      [PostId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'registerDevice' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'registerPushToken' : IDL.Func([IDL.Text], [], []),
  'registerWithPassword' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'removeDevice' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'removeFromCloseFriends' : IDL.Func(
      [UserId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'removeReaction' : IDL.Func(
      [PostId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'removeStoryFromHighlight' : IDL.Func(
      [HighlightId, StoryId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'replyToNote' : IDL.Func(
      [UserId, IDL.Text],
      [IDL.Variant({ 'ok' : MessageId, 'err' : IDL.Text })],
      [],
    ),
  'searchByHashtag' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
  'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
  'sendMessage' : IDL.Func(
      [UserId, IDL.Text, IDL.Opt(PostId)],
      [IDL.Variant({ 'ok' : MessageId, 'err' : IDL.Text })],
      [],
    ),
  'toggleLike' : IDL.Func(
      [PostId],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'toggleSave' : IDL.Func(
      [PostId],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'unblockUser' : IDL.Func([UserId], [], []),
  'unfollowUser' : IDL.Func(
      [UserId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'unlikeComment' : IDL.Func(
      [PostId, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'unlikeNote' : IDL.Func(
      [UserId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'unmuteUser' : IDL.Func([UserId], [], []),
  'unpinPost' : IDL.Func(
      [PostId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'unregisterPushToken' : IDL.Func([], [], []),
  'updateActivityStatus' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateHighlight' : IDL.Func(
      [HighlightId, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'uploadFile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'viewStory' : IDL.Func(
      [StoryId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'votePoll' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PostId = IDL.Nat;
  const CommentId = IDL.Nat;
  const HighlightId = IDL.Nat;
  const StoryId = IDL.Nat;
  const UserId = IDL.Principal;
  const NoteAudience = IDL.Variant({
    'MutualFollowers' : IDL.Null,
    'CloseFriends' : IDL.Null,
  });
  const Story = IDL.Record({
    'id' : StoryId,
    'songArtist' : IDL.Opt(IDL.Text),
    'songTitle' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'author' : UserId,
    'imageUrl' : IDL.Text,
    'caption' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'createdAt' : IDL.Int,
    'avatarUrl' : IDL.Text,
  });
  const StoryWithUser = IDL.Record({
    'story' : Story,
    'authorProfile' : IDL.Opt(UserProfile),
  });
  const ActivityStatus = IDL.Record({
    'isOnline' : IDL.Bool,
    'lastSeen' : IDL.Int,
  });
  const Comment = IDL.Record({
    'id' : CommentId,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'author' : UserId,
    'postId' : PostId,
  });
  const MessageId = IDL.Nat;
  const Message = IDL.Record({
    'id' : MessageId,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'toUser' : UserId,
    'fromUser' : UserId,
    'sharedPostId' : IDL.Opt(PostId),
  });
  const ConversationSummary = IDL.Record({
    'userId' : UserId,
    'lastMessage' : IDL.Opt(Message),
    'profile' : IDL.Opt(UserProfile),
  });
  const Post = IDL.Record({
    'id' : PostId,
    'songArtist' : IDL.Opt(IDL.Text),
    'hashtags' : IDL.Vec(IDL.Text),
    'imageUrls' : IDL.Vec(IDL.Text),
    'songTitle' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'isReel' : IDL.Bool,
    'author' : UserId,
    'imageUrl' : IDL.Text,
    'caption' : IDL.Text,
  });
  const Note = IDL.Record({
    'expiresAt' : IDL.Int,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'audience' : NoteAudience,
    'author' : UserId,
  });
  const NoteWithAuthor = IDL.Record({
    'likeCount' : IDL.Nat,
    'note' : Note,
    'authorProfile' : IDL.Opt(UserProfile),
  });
  const Highlight = IDL.Record({
    'id' : HighlightId,
    'title' : IDL.Text,
    'owner' : UserId,
    'createdAt' : IDL.Int,
    'coverUrl' : IDL.Text,
    'storyIds' : IDL.Vec(StoryId),
  });
  const DeviceInfo = IDL.Record({
    'deviceLabel' : IDL.Text,
    'addedAt' : IDL.Int,
    'deviceId' : IDL.Text,
    'principalId' : IDL.Text,
  });
  const NotificationId = IDL.Nat;
  const Notification = IDL.Record({
    'id' : NotificationId,
    'kind' : IDL.Text,
    'createdAt' : IDL.Int,
    'isRead' : IDL.Bool,
    'toUser' : UserId,
    'fromUser' : UserId,
    'postId' : IDL.Opt(PostId),
  });
  
  return IDL.Service({
    'addComment' : IDL.Func(
        [PostId, IDL.Text],
        [IDL.Variant({ 'ok' : CommentId, 'err' : IDL.Text })],
        [],
      ),
    'addQuestion' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'addReaction' : IDL.Func(
        [PostId, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'addStoryToHighlight' : IDL.Func(
        [HighlightId, StoryId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'addToCloseFriends' : IDL.Func(
        [UserId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'answerQuestion' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'authenticateWithPassword' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        ['query'],
      ),
    'blockUser' : IDL.Func([UserId], [], []),
    'createCarouselPost' : IDL.Func(
        [
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Variant({ 'ok' : PostId, 'err' : IDL.Text })],
        [],
      ),
    'createHighlight' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : HighlightId, 'err' : IDL.Text })],
        [],
      ),
    'createNote' : IDL.Func(
        [IDL.Text, NoteAudience],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'createPoll' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'createPost' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Bool,
        ],
        [IDL.Variant({ 'ok' : PostId, 'err' : IDL.Text })],
        [],
      ),
    'createProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'createQuestion' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'createStory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : StoryId, 'err' : IDL.Text })],
        [],
      ),
    'deleteHighlight' : IDL.Func(
        [HighlightId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteNote' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'downloadFile' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(IDL.Nat8), 'err' : IDL.Text })],
        ['query'],
      ),
    'followUser' : IDL.Func(
        [UserId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getActiveStories' : IDL.Func([], [IDL.Vec(StoryWithUser)], ['query']),
    'getActivityStatus' : IDL.Func([UserId], [ActivityStatus], ['query']),
    'getActivityStatusBatch' : IDL.Func(
        [IDL.Vec(UserId)],
        [IDL.Vec(IDL.Tuple(UserId, ActivityStatus))],
        ['query'],
      ),
    'getAllSetways' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getBlockedUsers' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
    'getCloseFriends' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCommentLikes' : IDL.Func([PostId, IDL.Nat], [IDL.Nat], ['query']),
    'getComments' : IDL.Func([PostId], [IDL.Vec(Comment)], ['query']),
    'getConversation' : IDL.Func([UserId], [IDL.Vec(Message)], ['query']),
    'getConversationList' : IDL.Func(
        [],
        [IDL.Vec(ConversationSummary)],
        ['query'],
      ),
    'getExploreFeed' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getFollowers' : IDL.Func([UserId], [IDL.Vec(UserProfile)], ['query']),
    'getFollowersNotes' : IDL.Func([], [IDL.Vec(NoteWithAuthor)], ['query']),
    'getFollowing' : IDL.Func([UserId], [IDL.Vec(UserProfile)], ['query']),
    'getHighlights' : IDL.Func([UserId], [IDL.Vec(Highlight)], ['query']),
    'getHomeFeed' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getLikeCount' : IDL.Func([PostId], [IDL.Nat], ['query']),
    'getMutedUsers' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
    'getMyDevices' : IDL.Func([], [IDL.Vec(DeviceInfo)], ['query']),
    'getMyNote' : IDL.Func([], [IDL.Opt(Note)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getMyPushToken' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getNoteLikes' : IDL.Func([UserId], [IDL.Vec(IDL.Principal)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPasswordUserPrincipal' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getPinnedPosts' : IDL.Func([UserId], [IDL.Vec(Post)], ['query']),
    'getPollResults' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'userVote' : IDL.Opt(IDL.Nat),
              'question' : IDL.Text,
              'votes' : IDL.Vec(IDL.Nat),
              'options' : IDL.Vec(IDL.Text),
            })
          ),
        ],
        ['query'],
      ),
    'getPost' : IDL.Func([PostId], [IDL.Opt(Post)], ['query']),
    'getPostImages' : IDL.Func([PostId], [IDL.Vec(IDL.Text)], ['query']),
    'getPostsByUser' : IDL.Func([UserId], [IDL.Vec(Post)], ['query']),
    'getProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'getProfileByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getQuestionAnswers' : IDL.Func(
        [IDL.Text],
        [
          IDL.Vec(
            IDL.Record({
              'answerer' : IDL.Text,
              'answer' : IDL.Text,
              'timestamp' : IDL.Int,
            })
          ),
        ],
        ['query'],
      ),
    'getReactions' : IDL.Func(
        [PostId],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getReelsFeed' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
    'getSavedPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getStories' : IDL.Func([UserId], [IDL.Vec(Story)], ['query']),
    'getStory' : IDL.Func([StoryId], [IDL.Opt(Story)], ['query']),
    'getTrendingHashtags' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'isBlocked' : IDL.Func([UserId], [IDL.Bool], ['query']),
    'isCloseFriend' : IDL.Func([UserId], [IDL.Bool], ['query']),
    'isCommentLiked' : IDL.Func([PostId, IDL.Nat], [IDL.Bool], ['query']),
    'isDeviceRegistered' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isFollowing' : IDL.Func([UserId], [IDL.Bool], ['query']),
    'isLiked' : IDL.Func([PostId], [IDL.Bool], ['query']),
    'isMuted' : IDL.Func([UserId], [IDL.Bool], ['query']),
    'likeComment' : IDL.Func(
        [PostId, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'likeNote' : IDL.Func(
        [UserId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'markNotificationsRead' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'muteUser' : IDL.Func([UserId], [], []),
    'pinPost' : IDL.Func(
        [PostId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'registerDevice' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'registerPushToken' : IDL.Func([IDL.Text], [], []),
    'registerWithPassword' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'removeDevice' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'removeFromCloseFriends' : IDL.Func(
        [UserId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'removeReaction' : IDL.Func(
        [PostId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'removeStoryFromHighlight' : IDL.Func(
        [HighlightId, StoryId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'replyToNote' : IDL.Func(
        [UserId, IDL.Text],
        [IDL.Variant({ 'ok' : MessageId, 'err' : IDL.Text })],
        [],
      ),
    'searchByHashtag' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
    'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
    'sendMessage' : IDL.Func(
        [UserId, IDL.Text, IDL.Opt(PostId)],
        [IDL.Variant({ 'ok' : MessageId, 'err' : IDL.Text })],
        [],
      ),
    'toggleLike' : IDL.Func(
        [PostId],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'toggleSave' : IDL.Func(
        [PostId],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'unblockUser' : IDL.Func([UserId], [], []),
    'unfollowUser' : IDL.Func(
        [UserId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'unlikeComment' : IDL.Func(
        [PostId, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'unlikeNote' : IDL.Func(
        [UserId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'unmuteUser' : IDL.Func([UserId], [], []),
    'unpinPost' : IDL.Func(
        [PostId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'unregisterPushToken' : IDL.Func([], [], []),
    'updateActivityStatus' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateHighlight' : IDL.Func(
        [HighlightId, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'uploadFile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'viewStory' : IDL.Func(
        [StoryId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'votePoll' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };