/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityStatus { 'isOnline' : boolean, 'lastSeen' : bigint }
export interface Comment {
  'id' : CommentId,
  'createdAt' : bigint,
  'text' : string,
  'author' : UserId,
  'postId' : PostId,
}
export type CommentId = bigint;
export interface ConversationSummary {
  'userId' : UserId,
  'lastMessage' : [] | [Message],
  'profile' : [] | [UserProfile],
}
export interface DeviceInfo {
  'deviceLabel' : string,
  'addedAt' : bigint,
  'deviceId' : string,
  'principalId' : string,
}
export interface Highlight {
  'id' : HighlightId,
  'title' : string,
  'owner' : UserId,
  'createdAt' : bigint,
  'coverUrl' : string,
  'storyIds' : Array<StoryId>,
}
export type HighlightId = bigint;
export interface Message {
  'id' : MessageId,
  'createdAt' : bigint,
  'text' : string,
  'toUser' : UserId,
  'fromUser' : UserId,
  'sharedPostId' : [] | [PostId],
}
export type MessageId = bigint;
export interface Note {
  'expiresAt' : bigint,
  'createdAt' : bigint,
  'text' : string,
  'audience' : NoteAudience,
  'author' : UserId,
}
export type NoteAudience = { 'MutualFollowers' : null } |
  { 'CloseFriends' : null };
export interface NoteWithAuthor {
  'likeCount' : bigint,
  'note' : Note,
  'authorProfile' : [] | [UserProfile],
}
export interface Notification {
  'id' : NotificationId,
  'kind' : string,
  'createdAt' : bigint,
  'isRead' : boolean,
  'toUser' : UserId,
  'fromUser' : UserId,
  'postId' : [] | [PostId],
}
export type NotificationId = bigint;
export interface Post {
  'id' : PostId,
  'songArtist' : [] | [string],
  'hashtags' : Array<string>,
  'imageUrls' : Array<string>,
  'songTitle' : [] | [string],
  'createdAt' : bigint,
  'isReel' : boolean,
  'author' : UserId,
  'imageUrl' : string,
  'caption' : string,
}
export type PostId = bigint;
export interface Story {
  'id' : StoryId,
  'songArtist' : [] | [string],
  'songTitle' : [] | [string],
  'createdAt' : bigint,
  'author' : UserId,
  'imageUrl' : string,
  'caption' : string,
}
export type StoryId = bigint;
export interface StoryWithUser {
  'story' : Story,
  'authorProfile' : [] | [UserProfile],
}
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'bio' : string,
  'username' : string,
  'displayName' : string,
  'createdAt' : bigint,
  'avatarUrl' : string,
}
export interface _SERVICE {
  'addComment' : ActorMethod<
    [PostId, string],
    { 'ok' : CommentId } |
      { 'err' : string }
  >,
  'addQuestion' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'addReaction' : ActorMethod<
    [PostId, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'addStoryToHighlight' : ActorMethod<
    [HighlightId, StoryId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'addToCloseFriends' : ActorMethod<
    [UserId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'answerQuestion' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'authenticateWithPassword' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'blockUser' : ActorMethod<[UserId], undefined>,
  'createCarouselPost' : ActorMethod<
    [Array<string>, string, Array<string>, [] | [string], [] | [string]],
    { 'ok' : PostId } |
      { 'err' : string }
  >,
  'createHighlight' : ActorMethod<
    [string, string],
    { 'ok' : HighlightId } |
      { 'err' : string }
  >,
  'createNote' : ActorMethod<
    [string, NoteAudience],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'createPoll' : ActorMethod<
    [string, string, Array<string>],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'createPost' : ActorMethod<
    [string, string, Array<string>, [] | [string], [] | [string], boolean],
    { 'ok' : PostId } |
      { 'err' : string }
  >,
  'createProfile' : ActorMethod<
    [string, string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'createQuestion' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'createStory' : ActorMethod<
    [string, string, [] | [string], [] | [string]],
    { 'ok' : StoryId } |
      { 'err' : string }
  >,
  'deleteHighlight' : ActorMethod<
    [HighlightId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteNote' : ActorMethod<[], { 'ok' : null } | { 'err' : string }>,
  'downloadFile' : ActorMethod<
    [string],
    { 'ok' : Uint8Array } |
      { 'err' : string }
  >,
  'followUser' : ActorMethod<[UserId], { 'ok' : null } | { 'err' : string }>,
  'getActiveStories' : ActorMethod<[], Array<StoryWithUser>>,
  'getActivityStatus' : ActorMethod<[UserId], ActivityStatus>,
  'getActivityStatusBatch' : ActorMethod<
    [Array<UserId>],
    Array<[UserId, ActivityStatus]>
  >,
  'getAllSetways' : ActorMethod<[], Array<string>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getBlockedUsers' : ActorMethod<[], Array<UserId>>,
  'getCloseFriends' : ActorMethod<[], Array<UserProfile>>,
  'getCommentLikes' : ActorMethod<[PostId, bigint], bigint>,
  'getComments' : ActorMethod<[PostId], Array<Comment>>,
  'getConversation' : ActorMethod<[UserId], Array<Message>>,
  'getConversationList' : ActorMethod<[], Array<ConversationSummary>>,
  'getExploreFeed' : ActorMethod<[], Array<Post>>,
  'getFollowers' : ActorMethod<[UserId], Array<UserProfile>>,
  'getFollowersNotes' : ActorMethod<[], Array<NoteWithAuthor>>,
  'getFollowing' : ActorMethod<[UserId], Array<UserProfile>>,
  'getHighlights' : ActorMethod<[UserId], Array<Highlight>>,
  'getHomeFeed' : ActorMethod<[], Array<Post>>,
  'getLikeCount' : ActorMethod<[PostId], bigint>,
  'getMutedUsers' : ActorMethod<[], Array<UserId>>,
  'getMyDevices' : ActorMethod<[], Array<DeviceInfo>>,
  'getMyNote' : ActorMethod<[], [] | [Note]>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getMyPushToken' : ActorMethod<[], [] | [string]>,
  'getNoteLikes' : ActorMethod<[UserId], Array<Principal>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPasswordUserPrincipal' : ActorMethod<[string], [] | [string]>,
  'getPinnedPosts' : ActorMethod<[UserId], Array<Post>>,
  'getPollResults' : ActorMethod<
    [string],
    [] | [
      {
        'userVote' : [] | [bigint],
        'question' : string,
        'votes' : Array<bigint>,
        'options' : Array<string>,
      }
    ]
  >,
  'getPost' : ActorMethod<[PostId], [] | [Post]>,
  'getPostImages' : ActorMethod<[PostId], Array<string>>,
  'getPostsByUser' : ActorMethod<[UserId], Array<Post>>,
  'getProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'getProfileByUsername' : ActorMethod<[string], [] | [UserProfile]>,
  'getQuestionAnswers' : ActorMethod<
    [string],
    Array<{ 'answerer' : string, 'answer' : string, 'timestamp' : bigint }>
  >,
  'getReactions' : ActorMethod<[PostId], Array<[string, bigint]>>,
  'getReelsFeed' : ActorMethod<[bigint, bigint], Array<Post>>,
  'getSavedPosts' : ActorMethod<[], Array<Post>>,
  'getStories' : ActorMethod<[UserId], Array<Story>>,
  'getStory' : ActorMethod<[StoryId], [] | [Story]>,
  'getTrendingHashtags' : ActorMethod<[bigint], Array<[string, bigint]>>,
  'isBlocked' : ActorMethod<[UserId], boolean>,
  'isCloseFriend' : ActorMethod<[UserId], boolean>,
  'isCommentLiked' : ActorMethod<[PostId, bigint], boolean>,
  'isDeviceRegistered' : ActorMethod<[string], boolean>,
  'isFollowing' : ActorMethod<[UserId], boolean>,
  'isLiked' : ActorMethod<[PostId], boolean>,
  'isMuted' : ActorMethod<[UserId], boolean>,
  'likeComment' : ActorMethod<
    [PostId, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'likeNote' : ActorMethod<[UserId], { 'ok' : null } | { 'err' : string }>,
  'markNotificationsRead' : ActorMethod<
    [],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'muteUser' : ActorMethod<[UserId], undefined>,
  'pinPost' : ActorMethod<[PostId], { 'ok' : null } | { 'err' : string }>,
  'registerDevice' : ActorMethod<[string, string], boolean>,
  'registerPushToken' : ActorMethod<[string], undefined>,
  'registerWithPassword' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'removeDevice' : ActorMethod<[string], boolean>,
  'removeFromCloseFriends' : ActorMethod<
    [UserId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'removeReaction' : ActorMethod<
    [PostId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'removeStoryFromHighlight' : ActorMethod<
    [HighlightId, StoryId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'replyToNote' : ActorMethod<
    [UserId, string],
    { 'ok' : MessageId } |
      { 'err' : string }
  >,
  'searchByHashtag' : ActorMethod<[string], Array<Post>>,
  'searchUsers' : ActorMethod<[string], Array<UserProfile>>,
  'sendMessage' : ActorMethod<
    [UserId, string, [] | [PostId]],
    { 'ok' : MessageId } |
      { 'err' : string }
  >,
  'toggleLike' : ActorMethod<[PostId], { 'ok' : boolean } | { 'err' : string }>,
  'toggleSave' : ActorMethod<[PostId], { 'ok' : boolean } | { 'err' : string }>,
  'unblockUser' : ActorMethod<[UserId], undefined>,
  'unfollowUser' : ActorMethod<[UserId], { 'ok' : null } | { 'err' : string }>,
  'unlikeComment' : ActorMethod<
    [PostId, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'unlikeNote' : ActorMethod<[UserId], { 'ok' : null } | { 'err' : string }>,
  'unmuteUser' : ActorMethod<[UserId], undefined>,
  'unpinPost' : ActorMethod<[PostId], { 'ok' : null } | { 'err' : string }>,
  'unregisterPushToken' : ActorMethod<[], undefined>,
  'updateActivityStatus' : ActorMethod<
    [],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateHighlight' : ActorMethod<
    [HighlightId, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateProfile' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'uploadFile' : ActorMethod<
    [string, string, Uint8Array],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'viewStory' : ActorMethod<[StoryId], { 'ok' : null } | { 'err' : string }>,
  'votePoll' : ActorMethod<
    [string, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];