/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface NoteWithAuthor {
    likeCount: bigint;
    note: Note;
    authorProfile?: UserProfile;
}
export type CommentId = bigint;
export interface Comment {
    id: CommentId;
    createdAt: bigint;
    text: string;
    author: UserId;
    postId: PostId;
}
export interface ActivityStatus {
    isOnline: boolean;
    lastSeen: bigint;
}
export type PostId = bigint;
export interface Story {
    id: StoryId;
    songArtist?: string;
    songTitle?: string;
    createdAt: bigint;
    author: UserId;
    imageUrl: string;
    caption: string;
}
export type StoryId = bigint;
export interface Highlight {
    id: HighlightId;
    title: string;
    owner: UserId;
    createdAt: bigint;
    coverUrl: string;
    storyIds: Array<StoryId>;
}
export interface StoryWithUser {
    story: Story;
    authorProfile?: UserProfile;
}
export type UserId = Principal;
export interface DeviceInfo {
    deviceLabel: string;
    addedAt: bigint;
    deviceId: string;
    principalId: string;
}
export type MessageId = bigint;
export interface Post {
    id: PostId;
    songArtist?: string;
    hashtags: Array<string>;
    imageUrls: Array<string>;
    songTitle?: string;
    createdAt: bigint;
    isReel: boolean;
    author: UserId;
    imageUrl: string;
    caption: string;
}
export type NotificationId = bigint;
export interface Notification {
    id: NotificationId;
    kind: string;
    createdAt: bigint;
    isRead: boolean;
    toUser: UserId;
    fromUser: UserId;
    postId?: PostId;
}
export interface Message {
    id: MessageId;
    createdAt: bigint;
    text: string;
    toUser: UserId;
    fromUser: UserId;
    sharedPostId?: PostId;
}
export type HighlightId = bigint;
export interface ConversationSummary {
    userId: UserId;
    lastMessage?: Message;
    profile?: UserProfile;
}
export interface UserProfile {
    id: UserId;
    bio: string;
    username: string;
    displayName: string;
    createdAt: bigint;
    avatarUrl: string;
}
export interface Note {
    expiresAt: bigint;
    createdAt: bigint;
    text: string;
    audience: NoteAudience;
    author: UserId;
}
export enum NoteAudience {
    MutualFollowers = "MutualFollowers",
    CloseFriends = "CloseFriends"
}
export interface backendInterface {
    addComment(postId: PostId, text: string): Promise<{
        __kind__: "ok";
        ok: CommentId;
    } | {
        __kind__: "err";
        err: string;
    }>;
    addQuestion(storyId: string, questionText: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    addReaction(postId: PostId, emoji: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    addStoryToHighlight(highlightId: HighlightId, storyId: StoryId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    addToCloseFriends(userId: UserId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    answerQuestion(questionId: string, answer: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    authenticateWithPassword(username: string, passwordHash: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    blockUser(targetUserId: UserId): Promise<void>;
    createCarouselPost(imageUrls: Array<string>, caption: string, hashtags: Array<string>, songTitle: string | null, songArtist: string | null): Promise<{
        __kind__: "ok";
        ok: PostId;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createHighlight(title: string, coverUrl: string): Promise<{
        __kind__: "ok";
        ok: HighlightId;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createNote(content: string, audience: NoteAudience): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createPoll(storyId: string, question: string, options: Array<string>): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createPost(imageUrl: string, caption: string, hashtags: Array<string>, songTitle: string | null, songArtist: string | null, isReel: boolean): Promise<{
        __kind__: "ok";
        ok: PostId;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createProfile(username: string, displayName: string, bio: string, avatarUrl: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createQuestion(storyId: string, questionText: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createStory(imageUrl: string, caption: string, songTitle: string | null, songArtist: string | null): Promise<{
        __kind__: "ok";
        ok: StoryId;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteHighlight(id: HighlightId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteNote(): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    downloadFile(_fileId: string): Promise<{
        __kind__: "ok";
        ok: Uint8Array;
    } | {
        __kind__: "err";
        err: string;
    }>;
    followUser(target: UserId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getActiveStories(): Promise<Array<StoryWithUser>>;
    getActivityStatus(userId: UserId): Promise<ActivityStatus>;
    getActivityStatusBatch(userIds: Array<UserId>): Promise<Array<[UserId, ActivityStatus]>>;
    getAllSetways(): Promise<Array<string>>;
    getAllUsers(): Promise<Array<UserProfile>>;
    getBlockedUsers(): Promise<Array<UserId>>;
    getCloseFriends(): Promise<Array<UserProfile>>;
    getCommentLikes(postId: PostId, commentId: bigint): Promise<bigint>;
    getComments(postId: PostId): Promise<Array<Comment>>;
    getConversation(otherUserId: UserId): Promise<Array<Message>>;
    getConversationList(): Promise<Array<ConversationSummary>>;
    getExploreFeed(): Promise<Array<Post>>;
    getFollowers(uid: UserId): Promise<Array<UserProfile>>;
    getFollowersNotes(): Promise<Array<NoteWithAuthor>>;
    getFollowing(uid: UserId): Promise<Array<UserProfile>>;
    getHighlights(uid: UserId): Promise<Array<Highlight>>;
    getHomeFeed(): Promise<Array<Post>>;
    getLikeCount(postId: PostId): Promise<bigint>;
    getMutedUsers(): Promise<Array<UserId>>;
    getMyDevices(): Promise<Array<DeviceInfo>>;
    getMyNote(): Promise<Note | null>;
    getMyProfile(): Promise<UserProfile | null>;
    getMyPushToken(): Promise<string | null>;
    getNoteLikes(authorId: UserId): Promise<Array<Principal>>;
    getNotifications(): Promise<Array<Notification>>;
    getPasswordUserPrincipal(username: string): Promise<string | null>;
    getPinnedPosts(uid: UserId): Promise<Array<Post>>;
    getPollResults(pollId: string): Promise<{
        userVote?: bigint;
        question: string;
        votes: Array<bigint>;
        options: Array<string>;
    } | null>;
    getPost(id: PostId): Promise<Post | null>;
    getPostImages(postId: PostId): Promise<Array<string>>;
    getPostsByUser(uid: UserId): Promise<Array<Post>>;
    getProfile(uid: UserId): Promise<UserProfile | null>;
    getProfileByUsername(username: string): Promise<UserProfile | null>;
    getQuestionAnswers(questionId: string): Promise<Array<{
        answerer: string;
        answer: string;
        timestamp: bigint;
    }>>;
    getReactions(postId: PostId): Promise<Array<[string, bigint]>>;
    getReelsFeed(limit: bigint, offset: bigint): Promise<Array<Post>>;
    getSavedPosts(): Promise<Array<Post>>;
    getStories(uid: UserId): Promise<Array<Story>>;
    getStory(storyId: StoryId): Promise<Story | null>;
    getTrendingHashtags(limit: bigint): Promise<Array<[string, bigint]>>;
    isBlocked(targetUserId: UserId): Promise<boolean>;
    isCloseFriend(userId: UserId): Promise<boolean>;
    isCommentLiked(postId: PostId, commentId: bigint): Promise<boolean>;
    isDeviceRegistered(deviceId: string): Promise<boolean>;
    isFollowing(target: UserId): Promise<boolean>;
    isLiked(postId: PostId): Promise<boolean>;
    isMuted(targetUserId: UserId): Promise<boolean>;
    likeComment(postId: PostId, commentId: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    likeNote(authorId: UserId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    markNotificationsRead(): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    muteUser(targetUserId: UserId): Promise<void>;
    pinPost(postId: PostId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    registerDevice(deviceId: string, deviceLabel: string): Promise<boolean>;
    registerPushToken(token: string): Promise<void>;
    registerWithPassword(username: string, passwordHash: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    removeDevice(deviceId: string): Promise<boolean>;
    removeFromCloseFriends(userId: UserId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    removeReaction(postId: PostId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    removeStoryFromHighlight(highlightId: HighlightId, storyId: StoryId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    replyToNote(authorId: UserId, replyText: string): Promise<{
        __kind__: "ok";
        ok: MessageId;
    } | {
        __kind__: "err";
        err: string;
    }>;
    searchByHashtag(hashtag: string): Promise<Array<Post>>;
    searchUsers(q: string): Promise<Array<UserProfile>>;
    sendMessage(recipientId: UserId, content: string, sharedPostId: PostId | null): Promise<{
        __kind__: "ok";
        ok: MessageId;
    } | {
        __kind__: "err";
        err: string;
    }>;
    toggleLike(postId: PostId): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    toggleSave(postId: PostId): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    unblockUser(targetUserId: UserId): Promise<void>;
    unfollowUser(target: UserId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    unlikeComment(postId: PostId, commentId: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    unlikeNote(authorId: UserId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    unmuteUser(targetUserId: UserId): Promise<void>;
    unpinPost(postId: PostId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    unregisterPushToken(): Promise<void>;
    updateActivityStatus(): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateHighlight(id: HighlightId, title: string, coverUrl: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateProfile(displayName: string, bio: string, avatarUrl: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    uploadFile(_name: string, _mime: string, _data: Uint8Array): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    viewStory(storyId: StoryId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    votePoll(pollId: string, optionIndex: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { CommentId as _CommentId, ConversationSummary as _ConversationSummary, HighlightId as _HighlightId, Message as _Message, MessageId as _MessageId, Note as _Note, NoteAudience as _NoteAudience, NoteWithAuthor as _NoteWithAuthor, Notification as _Notification, NotificationId as _NotificationId, Post as _Post, PostId as _PostId, Story as _Story, StoryId as _StoryId, StoryWithUser as _StoryWithUser, UserId as _UserId, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addComment(arg0: PostId, arg1: string): Promise<{
        __kind__: "ok";
        ok: CommentId;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addQuestion(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addQuestion(arg0, arg1);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQuestion(arg0, arg1);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async addReaction(arg0: PostId, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addReaction(arg0, arg1);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReaction(arg0, arg1);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async addStoryToHighlight(arg0: HighlightId, arg1: StoryId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addStoryToHighlight(arg0, arg1);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStoryToHighlight(arg0, arg1);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async addToCloseFriends(arg0: UserId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addToCloseFriends(arg0);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToCloseFriends(arg0);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async answerQuestion(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.answerQuestion(arg0, arg1);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.answerQuestion(arg0, arg1);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async authenticateWithPassword(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.authenticateWithPassword(arg0, arg1);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.authenticateWithPassword(arg0, arg1);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async blockUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.blockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockUser(arg0);
            return result;
        }
    }
    async createCarouselPost(arg0: Array<string>, arg1: string, arg2: Array<string>, arg3: string | null, arg4: string | null): Promise<{
        __kind__: "ok";
        ok: PostId;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createCarouselPost(arg0, arg1, arg2, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4));
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCarouselPost(arg0, arg1, arg2, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4));
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createHighlight(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: HighlightId;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createHighlight(arg0, arg1);
                return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHighlight(arg0, arg1);
            return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async createNote(arg0: string, arg1: NoteAudience): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createNote(arg0, to_candid_NoteAudience_n7(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNote(arg0, to_candid_NoteAudience_n7(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPoll(arg0: string, arg1: string, arg2: Array<string>): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createPoll(arg0, arg1, arg2);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPoll(arg0, arg1, arg2);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPost(arg0: string, arg1: string, arg2: Array<string>, arg3: string | null, arg4: string | null, arg5: boolean): Promise<{
        __kind__: "ok";
        ok: PostId;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(arg0, arg1, arg2, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4), arg5);
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(arg0, arg1, arg2, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4), arg5);
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProfile(arg0: string, arg1: string, arg2: string, arg3: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createProfile(arg0, arg1, arg2, arg3);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProfile(arg0, arg1, arg2, arg3);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createQuestion(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createQuestion(arg0, arg1);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createQuestion(arg0, arg1);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async createStory(arg0: string, arg1: string, arg2: string | null, arg3: string | null): Promise<{
        __kind__: "ok";
        ok: StoryId;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createStory(arg0, arg1, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg3));
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStory(arg0, arg1, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg3));
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteHighlight(arg0: HighlightId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHighlight(arg0);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHighlight(arg0);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteNote(): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNote();
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNote();
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async downloadFile(arg0: string): Promise<{
        __kind__: "ok";
        ok: Uint8Array;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.downloadFile(arg0);
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.downloadFile(arg0);
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async followUser(arg0: UserId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.followUser(arg0);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followUser(arg0);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveStories(): Promise<Array<StoryWithUser>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveStories();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveStories();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActivityStatus(arg0: UserId): Promise<ActivityStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityStatus(arg0);
            return result;
        }
    }
    async getActivityStatusBatch(arg0: Array<UserId>): Promise<Array<[UserId, ActivityStatus]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityStatusBatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityStatusBatch(arg0);
            return result;
        }
    }
    async getAllSetways(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSetways();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSetways();
            return result;
        }
    }
    async getAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getBlockedUsers(): Promise<Array<UserId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlockedUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlockedUsers();
            return result;
        }
    }
    async getCloseFriends(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCloseFriends();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCloseFriends();
            return result;
        }
    }
    async getCommentLikes(arg0: PostId, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommentLikes(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommentLikes(arg0, arg1);
            return result;
        }
    }
    async getComments(arg0: PostId): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComments(arg0);
            return result;
        }
    }
    async getConversation(arg0: UserId): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversation(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversation(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversationList(): Promise<Array<ConversationSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversationList();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversationList();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExploreFeed(): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExploreFeed();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExploreFeed();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowers(arg0: UserId): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowers(arg0);
            return result;
        }
    }
    async getFollowersNotes(): Promise<Array<NoteWithAuthor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowersNotes();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowersNotes();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowing(arg0: UserId): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowing(arg0);
            return result;
        }
    }
    async getHighlights(arg0: UserId): Promise<Array<Highlight>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHighlights(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHighlights(arg0);
            return result;
        }
    }
    async getHomeFeed(): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHomeFeed();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHomeFeed();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLikeCount(arg0: PostId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getLikeCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLikeCount(arg0);
            return result;
        }
    }
    async getMutedUsers(): Promise<Array<UserId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMutedUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMutedUsers();
            return result;
        }
    }
    async getMyDevices(): Promise<Array<DeviceInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyDevices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyDevices();
            return result;
        }
    }
    async getMyNote(): Promise<Note | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyNote();
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyNote();
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPushToken(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPushToken();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPushToken();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNoteLikes(arg0: UserId): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNoteLikes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNoteLikes(arg0);
            return result;
        }
    }
    async getNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPasswordUserPrincipal(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPasswordUserPrincipal(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPasswordUserPrincipal(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPinnedPosts(arg0: UserId): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPinnedPosts(arg0);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPinnedPosts(arg0);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPollResults(arg0: string): Promise<{
        userVote?: bigint;
        question: string;
        votes: Array<bigint>;
        options: Array<string>;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPollResults(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPollResults(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPost(arg0: PostId): Promise<Post | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPost(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPost(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPostImages(arg0: PostId): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostImages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostImages(arg0);
            return result;
        }
    }
    async getPostsByUser(arg0: UserId): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostsByUser(arg0);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostsByUser(arg0);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: UserId): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfileByUsername(arg0: string): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfileByUsername(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfileByUsername(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuestionAnswers(arg0: string): Promise<Array<{
        answerer: string;
        answer: string;
        timestamp: bigint;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestionAnswers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestionAnswers(arg0);
            return result;
        }
    }
    async getReactions(arg0: PostId): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReactions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReactions(arg0);
            return result;
        }
    }
    async getReelsFeed(arg0: bigint, arg1: bigint): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReelsFeed(arg0, arg1);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReelsFeed(arg0, arg1);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSavedPosts(): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSavedPosts();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSavedPosts();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStories(arg0: UserId): Promise<Array<Story>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStories(arg0);
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStories(arg0);
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStory(arg0: StoryId): Promise<Story | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStory(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStory(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrendingHashtags(arg0: bigint): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingHashtags(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingHashtags(arg0);
            return result;
        }
    }
    async isBlocked(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isBlocked(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isBlocked(arg0);
            return result;
        }
    }
    async isCloseFriend(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCloseFriend(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCloseFriend(arg0);
            return result;
        }
    }
    async isCommentLiked(arg0: PostId, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCommentLiked(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCommentLiked(arg0, arg1);
            return result;
        }
    }
    async isDeviceRegistered(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isDeviceRegistered(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isDeviceRegistered(arg0);
            return result;
        }
    }
    async isFollowing(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isFollowing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isFollowing(arg0);
            return result;
        }
    }
    async isLiked(arg0: PostId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isLiked(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isLiked(arg0);
            return result;
        }
    }
    async isMuted(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isMuted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isMuted(arg0);
            return result;
        }
    }
    async likeComment(arg0: PostId, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.likeComment(arg0, arg1);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeComment(arg0, arg1);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async likeNote(arg0: UserId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.likeNote(arg0);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeNote(arg0);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async markNotificationsRead(): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationsRead();
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationsRead();
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async muteUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.muteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.muteUser(arg0);
            return result;
        }
    }
    async pinPost(arg0: PostId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.pinPost(arg0);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pinPost(arg0);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerDevice(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.registerDevice(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerDevice(arg0, arg1);
            return result;
        }
    }
    async registerPushToken(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerPushToken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerPushToken(arg0);
            return result;
        }
    }
    async registerWithPassword(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.registerWithPassword(arg0, arg1);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerWithPassword(arg0, arg1);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeDevice(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeDevice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeDevice(arg0);
            return result;
        }
    }
    async removeFromCloseFriends(arg0: UserId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromCloseFriends(arg0);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromCloseFriends(arg0);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeReaction(arg0: PostId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.removeReaction(arg0);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeReaction(arg0);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeStoryFromHighlight(arg0: HighlightId, arg1: StoryId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.removeStoryFromHighlight(arg0, arg1);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeStoryFromHighlight(arg0, arg1);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async replyToNote(arg0: UserId, arg1: string): Promise<{
        __kind__: "ok";
        ok: MessageId;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.replyToNote(arg0, arg1);
                return from_candid_variant_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.replyToNote(arg0, arg1);
            return from_candid_variant_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchByHashtag(arg0: string): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchByHashtag(arg0);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchByHashtag(arg0);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchUsers(arg0: string): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchUsers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchUsers(arg0);
            return result;
        }
    }
    async sendMessage(arg0: UserId, arg1: string, arg2: PostId | null): Promise<{
        __kind__: "ok";
        ok: MessageId;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1, to_candid_opt_n47(this._uploadFile, this._downloadFile, arg2));
                return from_candid_variant_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1, to_candid_opt_n47(this._uploadFile, this._downloadFile, arg2));
            return from_candid_variant_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleLike(arg0: PostId): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleLike(arg0);
                return from_candid_variant_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleLike(arg0);
            return from_candid_variant_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleSave(arg0: PostId): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleSave(arg0);
                return from_candid_variant_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleSave(arg0);
            return from_candid_variant_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async unblockUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unblockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unblockUser(arg0);
            return result;
        }
    }
    async unfollowUser(arg0: UserId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollowUser(arg0);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollowUser(arg0);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async unlikeComment(arg0: PostId, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikeComment(arg0, arg1);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikeComment(arg0, arg1);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async unlikeNote(arg0: UserId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikeNote(arg0);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikeNote(arg0);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async unmuteUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unmuteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unmuteUser(arg0);
            return result;
        }
    }
    async unpinPost(arg0: PostId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.unpinPost(arg0);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unpinPost(arg0);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async unregisterPushToken(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unregisterPushToken();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unregisterPushToken();
            return result;
        }
    }
    async updateActivityStatus(): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateActivityStatus();
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateActivityStatus();
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateHighlight(arg0: HighlightId, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHighlight(arg0, arg1, arg2);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHighlight(arg0, arg1, arg2);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProfile(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1, arg2);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1, arg2);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async uploadFile(arg0: string, arg1: string, arg2: Uint8Array): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadFile(arg0, arg1, arg2);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadFile(arg0, arg1, arg2);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async viewStory(arg0: StoryId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.viewStory(arg0);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.viewStory(arg0);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async votePoll(arg0: string, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.votePoll(arg0, arg1);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.votePoll(arg0, arg1);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ConversationSummary_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConversationSummary): ConversationSummary {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Message_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_NoteAudience_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NoteAudience): NoteAudience {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_NoteWithAuthor_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NoteWithAuthor): NoteWithAuthor {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Note_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Note): Note {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Post_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Post): Post {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_StoryWithUser_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StoryWithUser): StoryWithUser {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Story_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Story): Story {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PostId]): PostId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Message]): Message | null {
    return value.length === 0 ? null : from_candid_Message_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Note]): Note | null {
    return value.length === 0 ? null : from_candid_Note_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        userVote: [] | [bigint];
        question: string;
        votes: Array<bigint>;
        options: Array<string>;
    }]): {
    userVote?: bigint;
    question: string;
    votes: Array<bigint>;
    options: Array<string>;
} | null {
    return value.length === 0 ? null : from_candid_record_n41(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Post]): Post | null {
    return value.length === 0 ? null : from_candid_Post_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Story]): Story | null {
    return value.length === 0 ? null : from_candid_Story_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    story: _Story;
    authorProfile: [] | [_UserProfile];
}): {
    story: Story;
    authorProfile?: UserProfile;
} {
    return {
        story: from_candid_Story_n14(_uploadFile, _downloadFile, value.story),
        authorProfile: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.authorProfile))
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _StoryId;
    songArtist: [] | [string];
    songTitle: [] | [string];
    createdAt: bigint;
    author: _UserId;
    imageUrl: string;
    caption: string;
}): {
    id: StoryId;
    songArtist?: string;
    songTitle?: string;
    createdAt: bigint;
    author: UserId;
    imageUrl: string;
    caption: string;
} {
    return {
        id: value.id,
        songArtist: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.songArtist)),
        songTitle: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.songTitle)),
        createdAt: value.createdAt,
        author: value.author,
        imageUrl: value.imageUrl,
        caption: value.caption
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MessageId;
    createdAt: bigint;
    text: string;
    toUser: _UserId;
    fromUser: _UserId;
    sharedPostId: [] | [_PostId];
}): {
    id: MessageId;
    createdAt: bigint;
    text: string;
    toUser: UserId;
    fromUser: UserId;
    sharedPostId?: PostId;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        text: value.text,
        toUser: value.toUser,
        fromUser: value.fromUser,
        sharedPostId: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.sharedPostId))
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: _UserId;
    lastMessage: [] | [_Message];
    profile: [] | [_UserProfile];
}): {
    userId: UserId;
    lastMessage?: Message;
    profile?: UserProfile;
} {
    return {
        userId: value.userId,
        lastMessage: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.lastMessage)),
        profile: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.profile))
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PostId;
    songArtist: [] | [string];
    hashtags: Array<string>;
    imageUrls: Array<string>;
    songTitle: [] | [string];
    createdAt: bigint;
    isReel: boolean;
    author: _UserId;
    imageUrl: string;
    caption: string;
}): {
    id: PostId;
    songArtist?: string;
    hashtags: Array<string>;
    imageUrls: Array<string>;
    songTitle?: string;
    createdAt: bigint;
    isReel: boolean;
    author: UserId;
    imageUrl: string;
    caption: string;
} {
    return {
        id: value.id,
        songArtist: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.songArtist)),
        hashtags: value.hashtags,
        imageUrls: value.imageUrls,
        songTitle: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.songTitle)),
        createdAt: value.createdAt,
        isReel: value.isReel,
        author: value.author,
        imageUrl: value.imageUrl,
        caption: value.caption
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    likeCount: bigint;
    note: _Note;
    authorProfile: [] | [_UserProfile];
}): {
    likeCount: bigint;
    note: Note;
    authorProfile?: UserProfile;
} {
    return {
        likeCount: value.likeCount,
        note: from_candid_Note_n32(_uploadFile, _downloadFile, value.note),
        authorProfile: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.authorProfile))
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expiresAt: bigint;
    createdAt: bigint;
    text: string;
    audience: _NoteAudience;
    author: _UserId;
}): {
    expiresAt: bigint;
    createdAt: bigint;
    text: string;
    audience: NoteAudience;
    author: UserId;
} {
    return {
        expiresAt: value.expiresAt,
        createdAt: value.createdAt,
        text: value.text,
        audience: from_candid_NoteAudience_n34(_uploadFile, _downloadFile, value.audience),
        author: value.author
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _NotificationId;
    kind: string;
    createdAt: bigint;
    isRead: boolean;
    toUser: _UserId;
    fromUser: _UserId;
    postId: [] | [_PostId];
}): {
    id: NotificationId;
    kind: string;
    createdAt: bigint;
    isRead: boolean;
    toUser: UserId;
    fromUser: UserId;
    postId?: PostId;
} {
    return {
        id: value.id,
        kind: value.kind,
        createdAt: value.createdAt,
        isRead: value.isRead,
        toUser: value.toUser,
        fromUser: value.fromUser,
        postId: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.postId))
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userVote: [] | [bigint];
    question: string;
    votes: Array<bigint>;
    options: Array<string>;
}): {
    userVote?: bigint;
    question: string;
    votes: Array<bigint>;
    options: Array<string>;
} {
    return {
        userVote: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.userVote)),
        question: value.question,
        votes: value.votes,
        options: value.options
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _CommentId;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: CommentId;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Uint8Array;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Uint8Array;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    MutualFollowers: null;
} | {
    CloseFriends: null;
}): NoteAudience {
    return "MutualFollowers" in value ? NoteAudience.MutualFollowers : "CloseFriends" in value ? NoteAudience.CloseFriends : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _MessageId;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: MessageId;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _PostId;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: PostId;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _HighlightId;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: HighlightId;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _StoryId;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: StoryId;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StoryWithUser>): Array<StoryWithUser> {
    return value.map((x)=>from_candid_StoryWithUser_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ConversationSummary>): Array<ConversationSummary> {
    return value.map((x)=>from_candid_ConversationSummary_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Post>): Array<Post> {
    return value.map((x)=>from_candid_Post_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NoteWithAuthor>): Array<NoteWithAuthor> {
    return value.map((x)=>from_candid_NoteWithAuthor_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Story>): Array<Story> {
    return value.map((x)=>from_candid_Story_n14(_uploadFile, _downloadFile, x));
}
function to_candid_NoteAudience_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NoteAudience): _NoteAudience {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostId | null): [] | [_PostId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NoteAudience): {
    MutualFollowers: null;
} | {
    CloseFriends: null;
} {
    return value == NoteAudience.MutualFollowers ? {
        MutualFollowers: null
    } : value == NoteAudience.CloseFriends ? {
        CloseFriends: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
